import "./globals.css";
import { Header } from "@/components/Header/Header";
import { UserProvider } from "@/contexts/UserContext";

export const metadata = {
  title: "weather-app",
  description: "Generated by Juan Cruz Rodríguez",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Header />
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
